### ISSUE TITLE
How about add CODE_OF_CONDUCT.md to bigpicture-light?

### ISSUE THREAD

**Issue by bbvch13531** [JuhoKang/bigpicture-light#34]
Type of issue
 - Doc

Description
- I think opensource project should have code of conduct. 😄
How about add CODE_OF_CONDUCT.md to bigpicture-light?
If this looks good on you, could I send PR that add CODE_OF_CONDUCT.md?

**Comment by JuhoKang** [comment]
@bbvch13531 Thank you for your kind interest with our project :D.
We were not aware of this and heard about this code of conduct the first time. 
After some search of what a code of conduct is, I consider it would be a good practice for our project. 
The PR will help us much as a base for our own one. I would be glad if you help us!
